package Siivoustiimi.test.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Siivoustiimi.test.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.03.28 19:37:16 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class KotityotTestTest {
}