package Siivoustiimi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Siivoustiimi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.03.28 12:52:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class JasenTest {



  // Generated by ComTest BEGIN
  /** testInt78 */
  @Test
  public void testInt78() {    // Jasen: 78
    Jasen timo1 = new Jasen(); 
    assertEquals("From: Jasen line: 80", 0, timo1.getId()); 
    timo1.rekisteroi(); 
    Jasen timo2 = new Jasen(); 
    timo2.rekisteroi(); 
    int n1 = timo1.getId(); 
    int n2 = timo2.getId(); 
    assertEquals("From: Jasen line: 86", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse106 */
  @Test
  public void testParse106() {    // Jasen: 106
    Jasen jasen = new Jasen(); 
    jasen.parse("5    |     Timo |  Kekkila     |Talvitie 4    |   11600   |    Vantaa   |   05013899304   |   41   |"); 
    assertEquals("From: Jasen line: 109", 5, jasen.getId()); 
    assertEquals("From: Jasen line: 110", true, jasen.toString().startsWith("5|Timo|Kekkila|Talvitie 4|"));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    jasen.rekisteroi(); 
    int n = jasen.getId(); 
    jasen.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    jasen.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Jasen line: 116", n+20+1, jasen.getId()); 
  } // Generated by ComTest END
}