package Siivoustiimi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Siivoustiimi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.02.21 16:32:15 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class JasenetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa44 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa44() throws SailoException {    // Jasenet: 44
    Jasenet jasenet = new Jasenet(); 
    Jasen timo1 = new Jasen(), timo2 = new Jasen(); 
    assertEquals("From: Jasenet line: 48", 0, jasenet.getLkm()); 
    jasenet.lisaa(timo1); assertEquals("From: Jasenet line: 49", 1, jasenet.getLkm()); 
    jasenet.lisaa(timo2); assertEquals("From: Jasenet line: 50", 2, jasenet.getLkm()); 
    jasenet.lisaa(timo1); assertEquals("From: Jasenet line: 51", 3, jasenet.getLkm()); 
    assertEquals("From: Jasenet line: 52", timo1, jasenet.anna(0)); 
    assertEquals("From: Jasenet line: 53", timo2, jasenet.anna(1)); 
    assertEquals("From: Jasenet line: 54", timo1, jasenet.anna(2)); 
    assertEquals("From: Jasenet line: 55", false, jasenet.anna(1) ==timo1); 
    assertEquals("From: Jasenet line: 56", true, jasenet.anna(1) ==timo2); 
    try {
    assertEquals("From: Jasenet line: 57", timo1, jasenet.anna(3)); 
    fail("Jasenet: 57 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    jasenet.lisaa(timo1); assertEquals("From: Jasenet line: 58", 4, jasenet.getLkm()); 
    jasenet.lisaa(timo1); assertEquals("From: Jasenet line: 59", 5, jasenet.getLkm()); 
    try {
    jasenet.lisaa(timo1); 
    fail("Jasenet: 60 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}