package Siivoustiimi.test;
// Generated by ComTest BEGIN
import Siivoustiimi.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.04.10 18:40:22 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class JasenetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa165 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa165() throws SailoException {    // Jasenet: 165
    Jasenet jasenet = new Jasenet(); 
    Jasen timo1 = new Jasen(), timo2 = new Jasen(); 
    assertEquals("From: Jasenet line: 169", 0, jasenet.getLkm()); 
    jasenet.lisaa(timo1); assertEquals("From: Jasenet line: 170", 1, jasenet.getLkm()); 
    jasenet.lisaa(timo2); assertEquals("From: Jasenet line: 171", 2, jasenet.getLkm()); 
    jasenet.lisaa(timo1); assertEquals("From: Jasenet line: 172", 3, jasenet.getLkm()); 
    assertEquals("From: Jasenet line: 173", timo1, jasenet.anna(0)); 
    assertEquals("From: Jasenet line: 174", timo2, jasenet.anna(1)); 
    assertEquals("From: Jasenet line: 175", timo1, jasenet.anna(2)); 
    assertEquals("From: Jasenet line: 176", false, jasenet.anna(1) ==timo1); 
    assertEquals("From: Jasenet line: 177", true, jasenet.anna(1) ==timo2); 
    try {
    assertEquals("From: Jasenet line: 178", timo1, jasenet.anna(3)); 
    fail("Jasenet: 178 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    jasenet.lisaa(timo1); assertEquals("From: Jasenet line: 179", 4, jasenet.getLkm()); 
    jasenet.lisaa(timo1); assertEquals("From: Jasenet line: 180", 5, jasenet.getLkm()); 
  } // Generated by ComTest END
}