package Siivoustiimi.test;
// Generated by ComTest BEGIN
import Siivoustiimi.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.03.16 17:19:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class KotityotTest {



  // Generated by ComTest BEGIN
  /** testIterator71 */
  @Test
  public void testIterator71() {    // Kotityot: 71
    Kotityot kotityot = new Kotityot(); 
    Kotityo imurointi1 = new Kotityo(2); kotityot.lisaa(imurointi1); 
    Kotityo imurointi2 = new Kotityo(1); kotityot.lisaa(imurointi2); 
    Kotityo imurointi3 = new Kotityo(2); kotityot.lisaa(imurointi3); 
    Kotityo imurointi4 = new Kotityo(1); kotityot.lisaa(imurointi4); 
    Kotityo lakaisu = new Kotityo(2); kotityot.lisaa(lakaisu); 
    Iterator<Kotityo> i2=kotityot.iterator(); 
    assertEquals("From: Kotityot line: 83", imurointi1, i2.next()); 
    assertEquals("From: Kotityot line: 84", imurointi2, i2.next()); 
    assertEquals("From: Kotityot line: 85", imurointi3, i2.next()); 
    assertEquals("From: Kotityot line: 86", imurointi4, i2.next()); 
    assertEquals("From: Kotityot line: 87", lakaisu, i2.next()); 
    try {
    assertEquals("From: Kotityot line: 88", lakaisu, i2.next()); 
    fail("Kotityot: 88 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKotityot103 */
  @Test
  public void testAnnaKotityot103() {    // Kotityot: 103
    Kotityot kotityot = new Kotityot(); 
    Kotityo imurointi1 = new Kotityo(2); kotityot.lisaa(imurointi1); 
    Kotityo imurointi2 = new Kotityo(1); kotityot.lisaa(imurointi2); 
    Kotityo imurointi3 = new Kotityo(2); kotityot.lisaa(imurointi3); 
    Kotityo imurointi4 = new Kotityo(2); kotityot.lisaa(imurointi4); 
    Kotityo imurointi5 = new Kotityo(2); kotityot.lisaa(imurointi5); 
    Kotityo imurointi6 = new Kotityo(3); kotityot.lisaa(imurointi6); 
    List<Kotityo> loytyneet; 
    loytyneet = kotityot.annaKotityot(5); 
    assertEquals("From: Kotityot line: 115", 0, loytyneet.size()); 
    loytyneet = kotityot.annaKotityot(1); 
    assertEquals("From: Kotityot line: 117", 1, loytyneet.size()); 
    loytyneet = kotityot.annaKotityot(2); 
    assertEquals("From: Kotityot line: 119", 4, loytyneet.size()); 
    assertEquals("From: Kotityot line: 120", true, loytyneet.get(0) == imurointi1); 
    assertEquals("From: Kotityot line: 121", true, loytyneet.get(1) == imurointi3); 
    loytyneet = kotityot.annaKotityot(2); 
    assertEquals("From: Kotityot line: 123", 4, loytyneet.size()); 
  } // Generated by ComTest END
}