package Siivoustiimi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Siivoustiimi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.06.08 12:19:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class KotityoTest {


  /**
   * testInt149
   */
  @Test
  public void testinPitaisiLuodaTunnusNumerotUusilleKotitoille() {    // Kotityo: 149
    Kotityo imurointi = new Kotityo();
    assertEquals("From: Kotityo line: 151", 0, imurointi.getKotityoID());
    imurointi.rekisteroi();
    Kotityo tiskaaminen = new Kotityo();
    tiskaaminen.rekisteroi();
    int n1 = imurointi.getKotityoID();
    int n2 = tiskaaminen.getKotityoID();
    assertEquals("From: Kotityo line: 157", n2 - 1, n1);
  }

  @Test
  public void testParse226() {    // Kotityo: 226
    Kotityo kotityo = new Kotityo();
    kotityo.parse("1               |Imurointi                | 3                  | 20        | 2024-01-07           |    1|");
    assertEquals("From: Kotityo line: 229", 1, kotityo.getKotityoID());
    assertEquals("From: Kotityo line: 230", true, kotityo.toString().startsWith("1|Imurointi|3|"));
    kotityo.rekisteroi();
    int n = kotityo.getKotityoID();
    kotityo.parse("" + (n + 20));  // Otetaan merkkijonosta vain tunnusnumero
    kotityo.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Kotityo line: 236", n + 20 + 1, kotityo.getKotityoID());

  }
}