package Siivoustiimi.test;
// Generated by ComTest BEGIN
import java.io.*;
import Siivoustiimi.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.04.15 21:45:06 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class KotityotTest {



  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta55 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta55() throws SailoException {    // Kotityot: 55
    Kotityot kotityot = new Kotityot(); 
    Kotityo imurointi21 = new Kotityo(); imurointi21.taytaKotityo(2); 
    Kotityo imurointi11 = new Kotityo(); imurointi11.taytaKotityo(1); 
    Kotityo imurointi22 = new Kotityo(); imurointi22.taytaKotityo(2); 
    Kotityo imurointi12 = new Kotityo(); imurointi12.taytaKotityo(1); 
    Kotityo imurointi23 = new Kotityo(); imurointi23.taytaKotityo(2); 
    String tiedNimi = "testiTiedosto"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    kotityot.lueTiedostosta(tiedNimi); 
    fail("Kotityot: 68 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kotityot.lisaa(imurointi21); 
    kotityot.lisaa(imurointi11); 
    kotityot.lisaa(imurointi22); 
    kotityot.lisaa(imurointi12); 
    kotityot.lisaa(imurointi23); 
    try {
    kotityot.tallenna(); 
    } catch (IOException e) {
    throw new RuntimeException(e); 
    }
    kotityot = new Kotityot(); 
    kotityot.lueTiedostosta(tiedNimi); 
    Iterator<Kotityo> i = kotityot.iterator(); 
    assertEquals("From: Kotityot line: 82", imurointi21.toString(), i.next().toString()); 
    assertEquals("From: Kotityot line: 83", imurointi11.toString(), i.next().toString()); 
    assertEquals("From: Kotityot line: 84", imurointi22.toString(), i.next().toString()); 
    assertEquals("From: Kotityot line: 85", imurointi12.toString(), i.next().toString()); 
    assertEquals("From: Kotityot line: 86", imurointi23.toString(), i.next().toString()); 
    assertEquals("From: Kotityot line: 87", false, i.hasNext()); 
    kotityot.lisaa(imurointi23); 
    try {
    kotityot.tallenna(); 
    } catch (IOException e) {
    throw new RuntimeException(e); 
    }
    assertEquals("From: Kotityot line: 94", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".bak"); 
    assertEquals("From: Kotityot line: 96", true, fbak.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator220 */
  @Test
  public void testIterator220() {    // Kotityot: 220
    Kotityot kotityot = new Kotityot(); 
    Kotityo imurointi1 = new Kotityo(2); kotityot.lisaa(imurointi1); 
    Kotityo imurointi2 = new Kotityo(1); kotityot.lisaa(imurointi2); 
    Kotityo imurointi3 = new Kotityo(2); kotityot.lisaa(imurointi3); 
    Kotityo imurointi4 = new Kotityo(1); kotityot.lisaa(imurointi4); 
    Kotityo lakaisu = new Kotityo(2); kotityot.lisaa(lakaisu); 
    Iterator<Kotityo> i2=kotityot.iterator(); 
    assertEquals("From: Kotityot line: 232", imurointi1, i2.next()); 
    assertEquals("From: Kotityot line: 233", imurointi2, i2.next()); 
    assertEquals("From: Kotityot line: 234", imurointi3, i2.next()); 
    assertEquals("From: Kotityot line: 235", imurointi4, i2.next()); 
    assertEquals("From: Kotityot line: 236", lakaisu, i2.next()); 
    try {
    assertEquals("From: Kotityot line: 237", lakaisu, i2.next()); 
    fail("Kotityot: 237 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKotityot251 */
  @Test
  public void testAnnaKotityot251() {    // Kotityot: 251
    Kotityot kotityot = new Kotityot(); 
    Kotityo imurointi1 = new Kotityo(2); kotityot.lisaa(imurointi1); 
    Kotityo imurointi2 = new Kotityo(1); kotityot.lisaa(imurointi2); 
    Kotityo imurointi3 = new Kotityo(2); kotityot.lisaa(imurointi3); 
    Kotityo imurointi4 = new Kotityo(2); kotityot.lisaa(imurointi4); 
    Kotityo imurointi5 = new Kotityo(2); kotityot.lisaa(imurointi5); 
    Kotityo imurointi6 = new Kotityo(3); kotityot.lisaa(imurointi6); 
    List<Kotityo> loytyneet; 
    loytyneet = kotityot.annaKotityot(5); 
    assertEquals("From: Kotityot line: 263", 0, loytyneet.size()); 
    loytyneet = kotityot.annaKotityot(1); 
    assertEquals("From: Kotityot line: 265", 1, loytyneet.size()); 
    loytyneet = kotityot.annaKotityot(2); 
    assertEquals("From: Kotityot line: 267", 4, loytyneet.size()); 
    assertEquals("From: Kotityot line: 268", true, loytyneet.get(0) == imurointi1); 
    assertEquals("From: Kotityot line: 269", true, loytyneet.get(1) == imurointi3); 
    loytyneet = kotityot.annaKotityot(2); 
    assertEquals("From: Kotityot line: 271", 4, loytyneet.size()); 
  } // Generated by ComTest END
}