package Siivoustiimi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Siivoustiimi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.04.19 10:26:51 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class KotityoTest {



  // Generated by ComTest BEGIN
  /** testInt127 */
  @Test
  public void testInt127() {    // Kotityo: 127
    Kotityo imurointi = new Kotityo(); 
    assertEquals("From: Kotityo line: 129", 0, imurointi.getKotityoID()); 
    imurointi.rekisteroi(); 
    Kotityo tiskaaminen = new Kotityo(); 
    tiskaaminen.rekisteroi(); 
    int n1 = imurointi.getKotityoID(); 
    int n2 = tiskaaminen.getKotityoID(); 
    assertEquals("From: Kotityo line: 135", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse204 */
  @Test
  public void testParse204() {    // Kotityo: 204
    Kotityo kotityo = new Kotityo(); 
    kotityo.parse("1               |Imurointi                | 3                  | 20        | 2024-01-07           |    1|"); 
    assertEquals("From: Kotityo line: 207", 1, kotityo.getKotityoID()); 
    assertEquals("From: Kotityo line: 208", true, kotityo.toString().startsWith("1|Imurointi|3|")); 
    kotityo.rekisteroi(); 
    int n = kotityo.getKotityoID(); 
    kotityo.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    kotityo.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Kotityo line: 214", n+20+1, kotityo.getKotityoID()); 
  } // Generated by ComTest END
}