package Siivoustiimi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Siivoustiimi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.04.19 10:27:13 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class SiivoustiimiTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa129 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa129() throws SailoException {    // Siivoustiimi: 129
    Siivoustiimi siivoustiimi = new Siivoustiimi(); 
    Jasen timo1 = new Jasen(); 
    Jasen timo2 = new Jasen(); 
    timo1.rekisteroi(); timo2.rekisteroi(); 
    assertEquals("From: Siivoustiimi line: 135", 0, siivoustiimi.getJasenia()); 
    siivoustiimi.lisaa(timo1); assertEquals("From: Siivoustiimi line: 136", 1, siivoustiimi.getJasenia()); 
    siivoustiimi.lisaa(timo2); assertEquals("From: Siivoustiimi line: 137", 2, siivoustiimi.getJasenia()); 
    siivoustiimi.lisaa(timo1); assertEquals("From: Siivoustiimi line: 138", 3, siivoustiimi.getJasenia()); 
    assertEquals("From: Siivoustiimi line: 139", timo1, siivoustiimi.annaJasen(0)); 
    assertEquals("From: Siivoustiimi line: 140", timo2, siivoustiimi.annaJasen(1)); 
    assertEquals("From: Siivoustiimi line: 141", timo1, siivoustiimi.annaJasen(2)); 
    try {
    assertEquals("From: Siivoustiimi line: 142", timo1, siivoustiimi.annaJasen(3)); 
    fail("Siivoustiimi: 142 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    siivoustiimi.lisaa(timo1); assertEquals("From: Siivoustiimi line: 143", 4, siivoustiimi.getJasenia()); 
    siivoustiimi.lisaa(timo1); assertEquals("From: Siivoustiimi line: 144", 5, siivoustiimi.getJasenia()); 
  } // Generated by ComTest END
}