package Siivoustiimi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Siivoustiimi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.04.17 19:28:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class SiivoustiimiTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa105 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa105() throws SailoException {    // Siivoustiimi: 105
    Siivoustiimi siivoustiimi = new Siivoustiimi(); 
    Jasen timo1 = new Jasen(); 
    Jasen timo2 = new Jasen(); 
    timo1.rekisteroi(); timo2.rekisteroi(); 
    assertEquals("From: Siivoustiimi line: 111", 0, siivoustiimi.getJasenia()); 
    siivoustiimi.lisaa(timo1); assertEquals("From: Siivoustiimi line: 112", 1, siivoustiimi.getJasenia()); 
    siivoustiimi.lisaa(timo2); assertEquals("From: Siivoustiimi line: 113", 2, siivoustiimi.getJasenia()); 
    siivoustiimi.lisaa(timo1); assertEquals("From: Siivoustiimi line: 114", 3, siivoustiimi.getJasenia()); 
    assertEquals("From: Siivoustiimi line: 115", timo1, siivoustiimi.annaJasen(0)); 
    assertEquals("From: Siivoustiimi line: 116", timo2, siivoustiimi.annaJasen(1)); 
    assertEquals("From: Siivoustiimi line: 117", timo1, siivoustiimi.annaJasen(2)); 
    try {
    assertEquals("From: Siivoustiimi line: 118", timo1, siivoustiimi.annaJasen(3)); 
    fail("Siivoustiimi: 118 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    siivoustiimi.lisaa(timo1); assertEquals("From: Siivoustiimi line: 119", 4, siivoustiimi.getJasenia()); 
    siivoustiimi.lisaa(timo1); assertEquals("From: Siivoustiimi line: 120", 5, siivoustiimi.getJasenia()); 
  } // Generated by ComTest END
}