package Siivoustiimi.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Siivoustiimi.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2024.04.10 10:04:29 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class SuoritusTest {



  // Generated by ComTest BEGIN
  /** testInt54 */
  @Test
  public void testInt54() {    // Suoritus: 54
    Suoritus suoritus1 = new Suoritus(); 
    assertEquals("From: Suoritus line: 56", 0, suoritus1.getSuoritusID()); 
    suoritus1.rekisteroiSuoritus(); 
    Suoritus suoritus2 = new Suoritus(); 
    suoritus2.rekisteroiSuoritus(); 
    int n1 = suoritus1.getSuoritusID(); 
    int n2 = suoritus2.getSuoritusID(); 
    assertEquals("From: Suoritus line: 62", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse90 */
  @Test
  public void testParse90() {    // Suoritus: 90
    Suoritus suoritus = new Suoritus(); 
    suoritus.parse("1               |30                  | 20.1.2024                  | 1                 1|"); 
    assertEquals("From: Suoritus line: 93", 1, suoritus.getSuoritusID()); 
    assertEquals("From: Suoritus line: 94", true, suoritus.toString().startsWith("1|30|")); 
    suoritus.rekisteroiSuoritus(); 
    int n = suoritus.getSuoritusID(); 
    suoritus.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    suoritus.rekisteroiSuoritus();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Suoritus line: 100", n+20+1, suoritus.getSuoritusID()); 
  } // Generated by ComTest END
}